language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

before_script:
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit -c app

notifications:
  email:
    -  joshua@20hz.nl

